/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biodiversitymanagerapp;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class ClimateActionGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClimateActionGUI.class.getName());
    //variable to use ClimateActionInterface
    private ClimateActionInterface myClimateAction;
    //variable to use FileManagementInterface
    private FileManagement fileManager;

    /**
     * Creates new form ClimateActionGUI
     */
    public ClimateActionGUI() {
        //initialize new FileManagement
        fileManager = new FileManagement();
        //new ClimateActionList, if the file exist load it otherwise default to a new Doubly Linked List ClimateActionList
        myClimateAction = fileManager.load("ClimateAction.dat", new ClimateActionList());
        initComponents();
        this.getContentPane().setBackground(Color.green);
        scopeLbl.setVisible(true);
        scopeTF.setVisible(true);
        nameLbl.setVisible(true);
        nameTF.setVisible(true);
        descriptionLbl.setVisible(true);
        descriptionTF.setVisible(true);
        resultLbl.setVisible(true);
        resultTF.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        environmentDataBtn = new javax.swing.JButton();
        priorityEnvironmentBtn = new javax.swing.JButton();
        scopeLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        scopeTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        descriptionTF = new javax.swing.JTextField();
        resultLbl = new javax.swing.JLabel();
        resultTF = new javax.swing.JTextField();
        getClimateActionData = new javax.swing.JButton();
        printListBtn = new javax.swing.JButton();
        sizeBtn = new javax.swing.JButton();
        insertClimateActionData = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        mainPageBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        title.setText("Climate Action");

        exitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        environmentDataBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        environmentDataBtn.setText("Environment Data");
        environmentDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                environmentDataBtnActionPerformed(evt);
            }
        });

        priorityEnvironmentBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        priorityEnvironmentBtn.setText("Priority Environment");
        priorityEnvironmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityEnvironmentBtnActionPerformed(evt);
            }
        });

        scopeLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        scopeLbl.setText("Scope");

        nameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameLbl.setText("Name of chosen focus");

        descriptionLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        descriptionLbl.setText(" Description of solutions applied");

        scopeTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        nameTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        descriptionTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        resultLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        resultLbl.setText("Result");

        getClimateActionData.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getClimateActionData.setText("Get Climate Action Data");
        getClimateActionData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getClimateActionDataActionPerformed(evt);
            }
        });

        printListBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        printListBtn.setText("Display All Cimate Action Data");
        printListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printListBtnActionPerformed(evt);
            }
        });

        sizeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sizeBtn.setText("Number of stored Climate Action Data");
        sizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeBtnActionPerformed(evt);
            }
        });

        insertClimateActionData.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        insertClimateActionData.setText("Insert Climate Action Data");
        insertClimateActionData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertClimateActionDataActionPerformed(evt);
            }
        });

        nextBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        previousBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        mainPageBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        mainPageBtn.setText("Main Page");
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        removeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        removeBtn.setText("Delete Climate Action");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(mainPageBtn)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(environmentDataBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priorityEnvironmentBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(resultLbl)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl)
                            .addComponent(scopeLbl))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(descriptionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(resultTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(scopeTF))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousBtn)
                        .addGap(47, 47, 47)
                        .addComponent(nextBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertClimateActionData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sizeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getClimateActionData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(title)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scopeLbl)
                    .addComponent(scopeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getClimateActionData))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(printListBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLbl)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sizeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertClimateActionData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultLbl)
                    .addComponent(removeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn)
                    .addComponent(previousBtn)
                    .addComponent(clearBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(environmentDataBtn)
                    .addComponent(priorityEnvironmentBtn)
                    .addComponent(mainPageBtn))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //go to Environment Data section
    private void environmentDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_environmentDataBtnActionPerformed
        // TODO add your handling code here:
        fileManager.save(myClimateAction, "ClimateAction.dat");
        new EnvironmentDataGUI().setVisible(true);
        //this.setVisible(false);
        //closes window properly, releases memory while setVisible keeps memory, overwrites save and inconsisten file loading
        this.dispose();
    }//GEN-LAST:event_environmentDataBtnActionPerformed
    //go to Priority Environment section
    private void priorityEnvironmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityEnvironmentBtnActionPerformed
        // TODO add your handling code here:
        fileManager.save(myClimateAction, "ClimateAction.dat");
        new PriorityEnvironmentGUI().setVisible(true);
        //this.setVisible(false);
        //closes window properly, releases memory while setVisible keeps memory, overwrites save and inconsisten file loading
        this.dispose();
    }//GEN-LAST:event_priorityEnvironmentBtnActionPerformed
    //exit from the application
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed
    //go back to BiodiversityManager app main page
    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        // TODO add your handling code here:
        new BiodiversityManagerGUI().setVisible(true);
        //this.setVisible(false);
        //closes window properly, releases memory while setVisible keeps memory, overwrites save and inconsisten file loading
        this.dispose();
    }//GEN-LAST:event_mainPageBtnActionPerformed
    //get climate action Data at a specific position
    private void getClimateActionDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getClimateActionDataActionPerformed
        // TODO add your handling code here:
        try {
            String input = JOptionPane.showInputDialog("Enter the position of the Climated Data you want.\n");
            if (input == null) {
                return;
            }
            int pos = Integer.parseInt(input.trim());
            //ensure valid position
            if (pos < 1) {
                displayTA.append("That is an invalid position.\n");
                //stop method if invalid
                return;
            }
            //check if the DLL is empty
            if (myClimateAction.isEmpty()) {
                displayTA.append("There is no Climate Action data stored to get.\n");
            } else if (myClimateAction.get(pos) == null) {
                displayTA.append("There is no Climate Action data stored at position." + pos + "\n");
            } else {
                displayTA.append(myClimateAction.get(pos) + "\n");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid number for position.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_getClimateActionDataActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        scopeTF.setText("");
        nameTF.setText("");
        descriptionTF.setText("");
        resultTF.setText("");
        displayTA.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed
    //insert ClimateAction data at a specific position in DLL
    private void insertClimateActionDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertClimateActionDataActionPerformed
        // TODO add your handling code here:
        try {
            //get the variable entered by user
            String scope = scopeTF.getText().trim();
            String name = nameTF.getText().trim();
            String description = descriptionTF.getText().trim();
            String result = resultTF.getText().trim();
            String input = JOptionPane.showInputDialog("Enter the position of the Climated Data you want.\n");
            if (input == null) {
                return;
            }
            int pos = Integer.parseInt(input.trim());
            //ensure valid position
            if (pos < 1) {
                displayTA.append("That is an invalid position.\n");
                //stop method if invalid
                return;
            }
            //initialize ClimateAction with variables
            ClimateAction ca = new ClimateAction(result, scope, name, description);

            //handle validation
            ca.validCommon();

            //save the ClimateAction data to DLL
            myClimateAction.add(pos, ca);

            //save ClimateAction with the data to file ClimateAction.dat
            fileManager.save(myClimateAction, "ClimateAction.dat");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid number for position.");
        }
        //catch and display message for any failed validation
        catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_insertClimateActionDataActionPerformed
    //print DLL ClimateActionList
    private void printListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printListBtnActionPerformed
        // TODO add your handling code here:
        //check if the DLL is empty
        if (myClimateAction.isEmpty()) {
            displayTA.append("There is no Climate Action data stored to display.\n");
        } else {
            displayTA.append(myClimateAction.printList() + "\n");
        }
    }//GEN-LAST:event_printListBtnActionPerformed
    //get the number of ClimateAction data stored in DLL
    private void sizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeBtnActionPerformed
        // TODO add your handling code here:
        if (myClimateAction.isEmpty()) {
            displayTA.append("There is no Climate Action data stored.\n");
        } else {
            //assign the size to iNumber
            int iNumber = myClimateAction.size();
            displayTA.append("There is " + iNumber + " of ClimateAction data stored.\n");
        }
    }//GEN-LAST:event_sizeBtnActionPerformed
    //remove Climate Action data by position
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        try {
            String input = JOptionPane.showInputDialog("Enter the position of the Climate Action Data you want.\n");
            if (input == null) {
                return;
            }
            int pos = Integer.parseInt(input.trim());
            //ensure valid position
            if (pos < 1) {
                displayTA.append("That is an invalid position.\n");
                //stop method if invalid
                return;
            }
            if (myClimateAction.isEmpty()) {
                displayTA.append("There is no Climate Action data to remove.\n");
            } else {
                myClimateAction.remove(pos);
                fileManager.save(myClimateAction, "ClimateAction.dat");
                displayTA.append("The Climate Action data at " + pos + " has been deleted.\n");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid number for position.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_removeBtnActionPerformed
    //button to allow moving to the next  ClimateAction in the DLL 
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:

        //clear display area before displaying ClimateAction data
        displayTA.setText("");

        //check if DLL is empty
        if (myClimateAction.isEmpty()) {
            displayTA.append("There is no Climate Action data view .\n");
        } else {
            Object next = myClimateAction.next();
            //handle null return
            if (next == null) {
                displayTA.append("There is no ClimateAction data after this to view to view.\n");
            } else {
                //display the next Climate Action Data
                displayTA.append(next + "\n");
            }
        }

    }//GEN-LAST:event_nextBtnActionPerformed
    //button to allow moving to the previous  ClimateAction in the DLL
    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        // TODO add your handling code here:

        //clear display area before displaying ClimateAction data
        displayTA.setText("");

        //check if DLL is empty
        if (myClimateAction.isEmpty()) {
            displayTA.append("There is no Climate Action data to view.\n");
        } else {
            Object prev = myClimateAction.prev();
            //handle null return
            if (prev == null) {
                displayTA.append("There is no previous ClimateAction data to view.\n");
            } else {
                //display the next Climate Action Data
                displayTA.append(prev + "\n");
            }
        }
    }//GEN-LAST:event_previousBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClimateActionGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton environmentDataBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton getClimateActionData;
    private javax.swing.JButton insertClimateActionData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton previousBtn;
    private javax.swing.JButton printListBtn;
    private javax.swing.JButton priorityEnvironmentBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JTextField resultTF;
    private javax.swing.JLabel scopeLbl;
    private javax.swing.JTextField scopeTF;
    private javax.swing.JButton sizeBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
