/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biodiversitymanagerapp;

import java.awt.Color;
import com.mycompany.biodiversitymanagerapp.EnvironmentDataGUI;
import com.mycompany.biodiversitymanagerapp.ClimateActionGUI;
import com.mycompany.biodiversitymanagerapp.BiodiversityManagerGUI;

/**
 *
 * @author moise
 */
public class PriorityEnvironmentGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PriorityEnvironmentGUI.class.getName());

    /**
     * Creates new form PriorityEnvironmentGUI
     */
    public PriorityEnvironmentGUI() {
        initComponents();
        this.getContentPane().setBackground(Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        scopeLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        reasonLbl = new javax.swing.JLabel();
        climateActionBtn = new javax.swing.JButton();
        environmentDataBtn = new javax.swing.JButton();
        insertPriorityEnvironment = new javax.swing.JButton();
        printListBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        sizeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        scopeTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        descriptionTF = new javax.swing.JTextField();
        reasonTF = new javax.swing.JTextField();
        priorityLbl = new javax.swing.JLabel();
        priorityTF = new javax.swing.JTextField();
        mainPageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        title.setText("Priority Environment");

        exitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setActionCommand("exitBtn");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        scopeLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        scopeLbl.setText("Scope");

        nameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameLbl.setText("Name of chosen focus");

        descriptionLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        descriptionLbl.setText(" Description of Environment");

        reasonLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        reasonLbl.setText("Reason for Priority");

        climateActionBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        climateActionBtn.setText("Climate Action");
        climateActionBtn.setActionCommand("climateActionBtn");
        climateActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                climateActionBtnActionPerformed(evt);
            }
        });

        environmentDataBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        environmentDataBtn.setText("Environment Data");
        environmentDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                environmentDataBtnActionPerformed(evt);
            }
        });

        insertPriorityEnvironment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        insertPriorityEnvironment.setText("Insert Priority Environment");

        printListBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        printListBtn.setText("Display Priority Environments");

        removeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        removeBtn.setText("Remove Environment with high Priority");

        sizeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sizeBtn.setText("Number of Priority Environments");

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        scopeTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        nameTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        descriptionTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        priorityLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        priorityLbl.setText("Set Priority");

        mainPageBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        mainPageBtn.setText("Main Page");
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainPageBtn)
                        .addGap(18, 18, 18)
                        .addComponent(environmentDataBtn)
                        .addGap(18, 18, 18)
                        .addComponent(climateActionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeBtn)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(283, 283, 283))))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertPriorityEnvironment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printListBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sizeBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descriptionLbl)
                                .addGap(30, 30, 30)
                                .addComponent(descriptionTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scopeLbl)
                                .addGap(146, 146, 146)
                                .addComponent(scopeTF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reasonLbl)
                                    .addComponent(priorityLbl))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reasonTF)
                                    .addComponent(priorityTF))))
                        .addGap(429, 429, 429))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(scopeLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scopeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(descriptionLbl)
                        .addGap(33, 33, 33))
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reasonLbl)
                    .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priorityLbl)
                    .addComponent(priorityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printListBtn)
                    .addComponent(sizeBtn)
                    .addComponent(insertPriorityEnvironment))
                .addGap(18, 18, 18)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(climateActionBtn)
                    .addComponent(environmentDataBtn)
                    .addComponent(mainPageBtn))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //go to Environment Data section
    private void environmentDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_environmentDataBtnActionPerformed
        // TODO add your handling code here:
        new EnvironmentDataGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_environmentDataBtnActionPerformed
    //go back to BiodiversityManager app main page 
    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        // TODO add your handling code here:
        new BiodiversityManagerGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainPageBtnActionPerformed
    //go to Climate Action Section
    private void climateActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climateActionBtnActionPerformed
        // TODO add your handling code here:
        new ClimateActionGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_climateActionBtnActionPerformed
    //exit from the application
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PriorityEnvironmentGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton climateActionBtn;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton environmentDataBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton insertPriorityEnvironment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton printListBtn;
    private javax.swing.JLabel priorityLbl;
    private javax.swing.JTextField priorityTF;
    private javax.swing.JLabel reasonLbl;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel scopeLbl;
    private javax.swing.JTextField scopeTF;
    private javax.swing.JButton sizeBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
