/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biodiversitymanagerapp;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class PriorityEnvironmentGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PriorityEnvironmentGUI.class.getName());
    //variable to use Priority Environment interface
    private PEInterface myPriorityEnvironment;
    //variable to use FileManagement
    private FileManagementInterface fileManager;

    //
    /**
     * Creates new form PriorityEnvironmentGUI
     */
    public PriorityEnvironmentGUI() {
        //initialize a new FileManagement
        fileManager = new FileManagement();
        //new PQEnvironment, if the file exist load it otherwise default to a new Queue
        myPriorityEnvironment = fileManager.load("PriorityEnvironment.dat", new PQEnvironment());
        initComponents();
        this.getContentPane().setBackground(Color.green);
        scopeLbl.setVisible(true);
        scopeTF.setVisible(true);
        nameLbl.setVisible(true);
        nameTF.setVisible(true);
        descriptionLbl.setVisible(true);
        descriptionTF.setVisible(true);
        reasonLbl.setVisible(true);
        reasonTF.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        scopeLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        reasonLbl = new javax.swing.JLabel();
        climateActionBtn = new javax.swing.JButton();
        environmentDataBtn = new javax.swing.JButton();
        insertPriorityEnvironment = new javax.swing.JButton();
        printQueueBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        sizeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        scopeTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        descriptionTF = new javax.swing.JTextField();
        reasonTF = new javax.swing.JTextField();
        priorityLbl = new javax.swing.JLabel();
        priorityTF = new javax.swing.JTextField();
        mainPageBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        getHighestPriorityEnvironment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        title.setText("Priority Environment");

        exitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setActionCommand("exitBtn");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        scopeLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        scopeLbl.setText("Scope");

        nameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameLbl.setText("Name of chosen focus");

        descriptionLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        descriptionLbl.setText(" Description of Environment");

        reasonLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        reasonLbl.setText("Reason for Priority");

        climateActionBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        climateActionBtn.setText("Climate Action");
        climateActionBtn.setActionCommand("climateActionBtn");
        climateActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                climateActionBtnActionPerformed(evt);
            }
        });

        environmentDataBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        environmentDataBtn.setText("Environment Data");
        environmentDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                environmentDataBtnActionPerformed(evt);
            }
        });

        insertPriorityEnvironment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        insertPriorityEnvironment.setText("Insert Priority Environment");
        insertPriorityEnvironment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPriorityEnvironmentActionPerformed(evt);
            }
        });

        printQueueBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        printQueueBtn.setText("Display Priority Environments");
        printQueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printQueueBtnActionPerformed(evt);
            }
        });

        removeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        removeBtn.setText("Remove Environment with high Priority");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        sizeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sizeBtn.setText("Number of Priority Environments");
        sizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeBtnActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        scopeTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        nameTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        descriptionTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        priorityLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        priorityLbl.setText("Set Priority");

        mainPageBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        mainPageBtn.setText("Main Page");
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        searchBtn.setText("Search for Priority Environment");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        getHighestPriorityEnvironment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getHighestPriorityEnvironment.setText("Get Highest Priority Environment");
        getHighestPriorityEnvironment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getHighestPriorityEnvironmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scopeLbl)
                            .addComponent(nameLbl))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTF)
                            .addComponent(scopeTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reasonLbl)
                            .addComponent(priorityLbl)
                            .addComponent(descriptionLbl))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionTF)
                            .addComponent(reasonTF, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(priorityTF))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainPageBtn)
                        .addGap(18, 18, 18)
                        .addComponent(environmentDataBtn)
                        .addGap(18, 18, 18)
                        .addComponent(climateActionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clearBtn)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertPriorityEnvironment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printQueueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sizeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(getHighestPriorityEnvironment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(scopeLbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scopeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLbl)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(descriptionLbl)
                                .addGap(33, 33, 33))
                            .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reasonLbl)
                            .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priorityLbl)
                            .addComponent(priorityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(insertPriorityEnvironment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn)
                .addGap(9, 9, 9)
                .addComponent(printQueueBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sizeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getHighestPriorityEnvironment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(climateActionBtn)
                    .addComponent(environmentDataBtn)
                    .addComponent(mainPageBtn))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //go to Environment Data section
    private void environmentDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_environmentDataBtnActionPerformed
        // TODO add your handling code here:
        new EnvironmentDataGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_environmentDataBtnActionPerformed
    //go back to BiodiversityManager app main page 
    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        // TODO add your handling code here:
        new BiodiversityManagerGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainPageBtnActionPerformed
    //go to Climate Action Section
    private void climateActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climateActionBtnActionPerformed
        // TODO add your handling code here:
        new ClimateActionGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_climateActionBtnActionPerformed
    //exit from the application
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed
    //insert new PriorityEnvironment data based on Priority given
    private void insertPriorityEnvironmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPriorityEnvironmentActionPerformed
        // TODO add your handling code here:
        //get the values entered by the  user
        String scope = scopeTF.getText();
        String name = nameTF.getText();
        String description = descriptionTF.getText();
        String reason = reasonTF.getText();
        //get priority
        int priority = Integer.parseInt(priorityTF.getText());

        //initializa PriorityEnvironment with its own variables
        PriorityEnvironment pe = new PriorityEnvironment(reason, scope, name, description);
        try{
        //validate the values
        pe.validCommon();
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

        //add to queue PQEnvironment
        myPriorityEnvironment.enqueue(priority, pe);
        //save to file
        fileManager.save(myPriorityEnvironment, "PriorityEnvironment.dat");
    }//GEN-LAST:event_insertPriorityEnvironmentActionPerformed
    //get the number of PriorityEnvironments in the queue
    private void sizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeBtnActionPerformed
        // TODO add your handling code here:
        //check if the queue is empty
        if (myPriorityEnvironment.isEmpty()) {
            displayTA.append("There are no Priority Environments stored in the Priority Environment Queue.\n");
        } else {
            displayTA.append("There are " + myPriorityEnvironment.size() + " Priority Environments stored in the Priority Queue Environment\n");
        }

    }//GEN-LAST:event_sizeBtnActionPerformed
    //remove the Priority Environment with the highest priority
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        //check if the queue is empty
        if (myPriorityEnvironment.isEmpty()) {
            displayTA.append("There are no Priority Environments to delete.\n");
        } else {
            myPriorityEnvironment.dequeue();
            fileManager.save(myPriorityEnvironment, "PriorityEnvironment.dat");
            displayTA.append("The highest Priority Environment as been deleted.\n");
        }
    }//GEN-LAST:event_removeBtnActionPerformed
    //display all Priority Environment stored in PEQEnvironment queue
    private void printQueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printQueueBtnActionPerformed
        // TODO add your handling code here:
        //check if queue is empty 
        if (myPriorityEnvironment.isEmpty()) {
            displayTA.append("There are no Priority Environments to display.\n");
        } else {
            displayTA.append(myPriorityEnvironment.printPEQueue() + "\n");
        }
    }//GEN-LAST:event_printQueueBtnActionPerformed
    //search by priority
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if (myPriorityEnvironment.isEmpty()) {
            displayTA.append("There are no Priority Environments stored to search.\n");
            //stop method if the queue is empty
            return;
        } else {
            int priorityKey = Integer.parseInt(JOptionPane.showInputDialog("Enter the priority of the Priority Environment you want to search. "));
            //ensure a valid position is enterd
            if (priorityKey < 0) {
                displayTA.append("That is not a valid position.\n");
                //stop the method if is an invalid positon
                return;
            }

            //variable to hold result of findByPriority method
            Object found = myPriorityEnvironment.findByPriority(priorityKey);
            if (found != null) {
                displayTA.append("The Priority Environment with " + priorityKey + " priority was found.\n " + found + "\n");
            } else {
                displayTA.append("There is no Priority Environment with that priority.\n");
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        scopeTF.setText("");
        nameTF.setText("");
        descriptionTF.setText("");
        reasonTF.setText("");
        priorityTF.setText("");
        displayTA.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed
    //get the Priority Environment with the highest priority
    private void getHighestPriorityEnvironmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getHighestPriorityEnvironmentActionPerformed
        // TODO add your handling code here:
        //check if queue is empty
        if (myPriorityEnvironment.isEmpty()) {
            displayTA.append("There are no Priority Environments stored to get.\n");
        } else {
            displayTA.append("The highest priority environment \n"+myPriorityEnvironment.frontData() + "\n");
        }
    }//GEN-LAST:event_getHighestPriorityEnvironmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PriorityEnvironmentGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton climateActionBtn;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton environmentDataBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton getHighestPriorityEnvironment;
    private javax.swing.JButton insertPriorityEnvironment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton printQueueBtn;
    private javax.swing.JLabel priorityLbl;
    private javax.swing.JTextField priorityTF;
    private javax.swing.JLabel reasonLbl;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel scopeLbl;
    private javax.swing.JTextField scopeTF;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton sizeBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
